# Configuration file for rubocop.

AllCops:
  TargetRubyVersion: 2.6.0

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Layout/LineLength:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Style/FrozenStringLiteralComment:
  Enabled: false
