# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 236e482a58ddc5d40086bdd819fd4c0164b8cea988ab85b514c4b2509220fcbd5ba71f2b73d68f1edfac03ee90efb00a3e7578bc007bceb7a3d8d5b04cbed87d

test:
  secret_key_base: b70276533bf13ecb83664ba83eb0686721f69974beb8e66d4eec9b509ce5ee981f417eefa502c9ef22086723722ba4c3f82e1c41ca9cacd471a0c3c2c6448cd8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
