# Configuration file for rubocop.

AllCops:
  TargetRubyVersion: 2.5.0

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 30
