# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.0'

# Main server.
gem 'puma', '~> 3.11'

# Rails.
gem 'rails', '~> 5.2.2', '>= 5.2.2.1'

# Styles gems.
gem 'webpacker'

# Database.
gem 'sqlite3'

# Reduces boot times through caching; required in config/boot.rb.
gem 'bootsnap', '>= 1.1.0', require: false

# Build JSON APIs with ease.
gem 'jbuilder', '~> 2.5'

# Manage crypted password for authentication.
# gem 'bcrypt'

# Generate Json Web Token.
# gem 'jwt'

# Manage jobs.
# gem 'sidekiq'
# gem 'sidekiq-cron'

# Manage cached data on redis server.
# gem 'redis'

# Security Rack middleware.
# gem 'rack-attack'

# Enforce system architecture with events.
# gem 'evnt', git: 'https://github.com/ideonetwork/evnt'

# Add generators helpers.
gem 'dakarai', git: 'https://github.com/ideonetwork/dakarai'

group :test, :development do
  # call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # get random data for seeds
  gem 'faker'
end

group :test do
  # adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
end

group :development do
  # develop
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
  # get pretty errors
  gem 'better_errors'
  # check code quality
  gem 'rubocop'
  gem 'rubycritic'
  # test security
  gem 'brakeman'
end

group :production do
  # add CORS support
  gem 'rack-cors'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
