# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

ruby '2.4.0'

# Main server.
gem 'puma', '~> 3.7'

# Rails.
gem 'rails', '~> 5.1.3'

# Styles gems.
gem 'jbuilder', '>= 2.5'
gem 'sass-rails', '>= 5.0'
gem 'uglifier', '>= 1.3.0'

# Manage cached data on redis server.
# gem 'redis'
# gem 'redis-namespace'
# gem 'redis-store'
# gem 'redis-rails'

# Database.
gem 'sqlite3'

# Manage crypted password for authentication.
gem 'bcrypt'

# Generate Json Web Token.
gem 'jwt'

# Upload files and media.
# gem 'paperclip'

# Manage jobs.
# gem 'sidekiq'

# Add Ideo SRL company helpers.
# gem 'ideo_rails', git: 'https://github.com/ideonetwork/ideo-rails'

# Enforce system architecture with events.
gem 'evnt', git: 'https://github.com/ideonetwork/ruby-evnt'

# Create admin panel with Lato.
# core module:
# gem 'lato_core', git: 'https://github.com/ideonetwork/lato-core'
# media module:
# gem 'lato_media', git: 'https://github.com/ideonetwork/lato-media'
# blog module:
# gem 'lato_blog', git: 'https://github.com/ideonetwork/lato-blog'

# Test gems
group :test do
  # ger random data for seeds
  gem 'faker'
end

# Development gems
group :development do
  # develop
  gem 'listen', '~> 3.1.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  # get pretty errors
  gem 'better_errors'
  # work better with console
  gem 'colorize'
  gem 'table_print'
  # get database documentation
  gem 'rails-erd'
  # check code quality
  gem 'rubocop'
  gem 'rubycritic'
end

# Production gems
group :production do
  # database
  gem 'mysql2'
  # add CORS support
  gem 'rack-cors'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'ideo_rails', path: '../'